export const EU_MEMBER_STATES = [
  {
    name: 'Austria',
    code: 'AT',
    flag: '🇦🇹',
    capital: 'Vienna',
    population: '9.1M',
    popRaw: 9.1,
    joined: 1995,
    gdp: '€470B',
    gdpRaw: 470,
    region: 'Central Europe',
    coordinates: { x: 480, y: 350 },
    desc: 'Known for rich cultural history, high quality of living, and green energy innovations.',
    sectors: ['Machinery', 'Tourism', 'Renewable Energy', 'Automotive']
  },
  {
    name: 'Belgium',
    code: 'BE',
    flag: '🇧🇪',
    capital: 'Brussels',
    population: '11.7M',
    popRaw: 11.7,
    joined: 1957,
    gdp: '€580B',
    gdpRaw: 580,
    region: 'Western Europe',
    coordinates: { x: 320, y: 280 },
    desc: 'De facto capital of the European Union, hosting major international headquarters.',
    sectors: ['Pharmaceuticals', 'Logistics', 'Chemicals', 'Financial Services']
  },
  {
    name: 'Bulgaria',
    code: 'BG',
    flag: '🇧🇬',
    capital: 'Sofia',
    population: '6.4M',
    popRaw: 6.4,
    joined: 2007,
    gdp: '€84B',
    gdpRaw: 84,
    region: 'Eastern Europe',
    coordinates: { x: 650, y: 450 },
    desc: 'Strategic Balkan nation with rapidly expanding tech hubs and ancient heritage.',
    sectors: ['IT Services', 'Mining', 'Agriculture', 'Tourism']
  },
  {
    name: 'Croatia',
    code: 'HR',
    flag: '🇭🇷',
    capital: 'Zagreb',
    population: '3.8M',
    popRaw: 3.8,
    joined: 2013,
    gdp: '€70B',
    gdpRaw: 70,
    region: 'Southern Europe',
    coordinates: { x: 520, y: 420 },
    desc: 'The EU\'s 28th member state, celebrated for maritime tourism, coastlines, and renewable power.',
    sectors: ['Tourism', 'Shipbuilding', 'Pharmaceuticals', 'Energy']
  },
  {
    name: 'Cyprus',
    code: 'CY',
    flag: '🇨🇾',
    capital: 'Nicosia',
    population: '0.9M',
    popRaw: 0.9,
    joined: 2004,
    gdp: '€28B',
    gdpRaw: 28,
    region: 'Southern Europe',
    coordinates: { x: 750, y: 650 },
    desc: 'Eastern Mediterranean financial, shipping, and tourism hub at the crossroads of continents.',
    sectors: ['Shipping', 'Financial Services', 'Tourism', 'Real Estate']
  },
  {
    name: 'Czech Republic',
    code: 'CZ',
    flag: '🇨🇿',
    capital: 'Prague',
    population: '10.9M',
    popRaw: 10.9,
    joined: 2004,
    gdp: '€290B',
    gdpRaw: 290,
    region: 'Central Europe',
    coordinates: { x: 500, y: 280 },
    desc: 'Central European industrial superpower with high-tech manufacturing and UNESCO heritage cities.',
    sectors: ['Automotive', 'Engineering', 'Electronics', 'Brewing & Tourism']
  },
  {
    name: 'Denmark',
    code: 'DK',
    flag: '🇩🇰',
    capital: 'Copenhagen',
    population: '5.9M',
    popRaw: 5.9,
    joined: 1973,
    gdp: '€370B',
    gdpRaw: 370,
    region: 'Northern Europe',
    coordinates: { x: 420, y: 200 },
    desc: 'Global pioneer in offshore wind power, green technology, social welfare, and life sciences.',
    sectors: ['Wind Energy', 'Pharmaceuticals', 'Shipping', 'Design & Architecture']
  },
  {
    name: 'Estonia',
    code: 'EE',
    flag: '🇪🇪',
    capital: 'Tallinn',
    population: '1.4M',
    popRaw: 1.4,
    joined: 2004,
    gdp: '€38B',
    gdpRaw: 38,
    region: 'Northern Europe',
    coordinates: { x: 640, y: 140 },
    desc: 'World leader in e-governance, digital identity, cybersecurity, and tech unicorn startups.',
    sectors: ['Software & Cybersecurity', 'E-Governance', 'Wood Products', 'Electronics']
  },
  {
    name: 'Finland',
    code: 'FI',
    flag: '🇫🇮',
    capital: 'Helsinki',
    population: '5.6M',
    popRaw: 5.6,
    joined: 1995,
    gdp: '€270B',
    gdpRaw: 270,
    region: 'Northern Europe',
    coordinates: { x: 600, y: 80 },
    desc: 'Renowned for world-class education, clean energy tech, telecommunications, and high standard of living.',
    sectors: ['CleanTech', 'Forestry & Paper', 'Telecom', 'Gaming & Software']
  },
  {
    name: 'France',
    code: 'FR',
    flag: '🇫🇷',
    capital: 'Paris',
    population: '68.1M',
    popRaw: 68.1,
    joined: 1957,
    gdp: '€2.8T',
    gdpRaw: 2800,
    region: 'Western Europe',
    coordinates: { x: 200, y: 400 },
    desc: 'Founding member, diplomatic centerpiece, and key industrial leader in aerospace, energy, and agriculture.',
    sectors: ['Aerospace', 'Luxury Goods', 'Nuclear Energy', 'Agriculture']
  },
  {
    name: 'Germany',
    code: 'DE',
    flag: '🇩🇪',
    capital: 'Berlin',
    population: '84.4M',
    popRaw: 84.4,
    joined: 1957,
    gdp: '€4.1T',
    gdpRaw: 4100,
    region: 'Western Europe',
    coordinates: { x: 400, y: 300 },
    desc: 'Europe\'s largest economy, global leader in automotive engineering, green transition, and industrial machinery.',
    sectors: ['Automotive', 'Chemicals', 'Precision Machinery', 'Renewable Tech']
  },
  {
    name: 'Greece',
    code: 'GR',
    flag: '🇬🇷',
    capital: 'Athens',
    population: '10.4M',
    popRaw: 10.4,
    joined: 1981,
    gdp: '€220B',
    gdpRaw: 220,
    region: 'Southern Europe',
    coordinates: { x: 600, y: 600 },
    desc: 'Cradle of Western democracy, commercial shipping leader, and premier Mediterranean travel destination.',
    sectors: ['Merchant Shipping', 'Tourism', 'Agriculture', 'Renewable Energy']
  },
  {
    name: 'Hungary',
    code: 'HU',
    flag: '🇭🇺',
    capital: 'Budapest',
    population: '9.6M',
    popRaw: 9.6,
    joined: 2004,
    gdp: '€180B',
    gdpRaw: 180,
    region: 'Central Europe',
    coordinates: { x: 550, y: 350 },
    desc: 'Central European manufacturing hub with specialized EV battery and automotive industrial corridors.',
    sectors: ['EV Batteries', 'Automotive', 'Pharmaceuticals', 'Electronics']
  },
  {
    name: 'Ireland',
    code: 'IE',
    flag: '🇮🇪',
    capital: 'Dublin',
    population: '5.3M',
    popRaw: 5.3,
    joined: 1973,
    gdp: '€500B',
    gdpRaw: 500,
    region: 'Western Europe',
    coordinates: { x: 150, y: 250 },
    desc: 'European headquarters for global technology and biopharmaceutical leaders with rapid GDP expansion.',
    sectors: ['Software & Cloud', 'Biopharmaceuticals', 'Fintech', 'Agri-food']
  },
  {
    name: 'Italy',
    code: 'IT',
    flag: '🇮🇹',
    capital: 'Rome',
    population: '58.9M',
    popRaw: 58.9,
    joined: 1957,
    gdp: '€2.1T',
    gdpRaw: 2100,
    region: 'Southern Europe',
    coordinates: { x: 450, y: 500 },
    desc: 'Founding member, home to the Treaty of Rome, powerhouse in luxury design, machinery, and gastronomy.',
    sectors: ['Fashion & Luxury', 'Precision Engineering', 'Tourism', 'Agri-business']
  },
  {
    name: 'Latvia',
    code: 'LV',
    flag: '🇱🇻',
    capital: 'Riga',
    population: '1.9M',
    popRaw: 1.9,
    joined: 2004,
    gdp: '€40B',
    gdpRaw: 40,
    region: 'Northern Europe',
    coordinates: { x: 620, y: 180 },
    desc: 'Baltic transit and financial bridge with growing green bioeconomy and digital service sectors.',
    sectors: ['Logistics', 'Wood Processing', 'Information Tech', 'Chemicals']
  },
  {
    name: 'Lithuania',
    code: 'LT',
    flag: '🇱🇹',
    capital: 'Vilnius',
    population: '2.9M',
    popRaw: 2.9,
    joined: 2004,
    gdp: '€70B',
    gdpRaw: 70,
    region: 'Northern Europe',
    coordinates: { x: 600, y: 200 },
    desc: 'Fintech capital of the Baltic region and international innovator in ultra-fast laser technology.',
    sectors: ['Fintech', 'Lasers & Optics', 'Biotech', 'Furniture']
  },
  {
    name: 'Luxembourg',
    code: 'LU',
    flag: '🇱🇺',
    capital: 'Luxembourg City',
    population: '0.66M',
    popRaw: 0.66,
    joined: 1957,
    gdp: '€82B',
    gdpRaw: 82,
    region: 'Western Europe',
    coordinates: { x: 350, y: 300 },
    desc: 'Founding member with world-leading GDP per capita, financial banking funds, and satellite telecom.',
    sectors: ['Investment Banking', 'Space Tech & Telecom', 'Steel', 'Legal Services']
  },
  {
    name: 'Malta',
    code: 'MT',
    flag: '🇲🇹',
    capital: 'Valletta',
    population: '0.53M',
    popRaw: 0.53,
    joined: 2004,
    gdp: '€18B',
    gdpRaw: 18,
    region: 'Southern Europe',
    coordinates: { x: 480, y: 650 },
    desc: 'Strategic Mediterranean island nation specializing in digital services, maritime register, and aviation.',
    sectors: ['iGaming & Digital Tech', 'Maritime Shipping', 'Tourism', 'Financial Services']
  },
  {
    name: 'Netherlands',
    code: 'NL',
    flag: '🇳🇱',
    capital: 'Amsterdam',
    population: '17.9M',
    popRaw: 17.9,
    joined: 1957,
    gdp: '€1.0T',
    gdpRaw: 1000,
    region: 'Western Europe',
    coordinates: { x: 350, y: 250 },
    desc: 'Founding member, gateway to Europe via Rotterdam, semiconductor equipment leader (ASML), and agri-tech pioneer.',
    sectors: ['Semiconductor Equipment', 'Logistics', 'High-Tech Agri', 'Finance']
  },
  {
    name: 'Poland',
    code: 'PL',
    flag: '🇵🇱',
    capital: 'Warsaw',
    population: '36.7M',
    popRaw: 36.7,
    joined: 2004,
    gdp: '€750B',
    gdpRaw: 750,
    region: 'Central Europe',
    coordinates: { x: 550, y: 250 },
    desc: 'Central Europe\'s largest economy, major regional logistics artery, and software development center.',
    sectors: ['IT & Game Dev', 'Automotive Parts', 'Furniture', 'Manufacturing']
  },
  {
    name: 'Portugal',
    code: 'PT',
    flag: '🇵🇹',
    capital: 'Lisbon',
    population: '10.5M',
    popRaw: 10.5,
    joined: 1986,
    gdp: '€260B',
    gdpRaw: 260,
    region: 'Southern Europe',
    coordinates: { x: 50, y: 550 },
    desc: 'Atlantic green transition pioneer with 70%+ renewable grid share, tech startup hub, and tourism destination.',
    sectors: ['Renewable Energy', 'Tech Startups', 'Textiles & Footwear', 'Tourism']
  },
  {
    name: 'Romania',
    code: 'RO',
    flag: '🇷🇴',
    capital: 'Bucharest',
    population: '19.0M',
    popRaw: 19.0,
    joined: 2007,
    gdp: '€320B',
    gdpRaw: 320,
    region: 'Eastern Europe',
    coordinates: { x: 650, y: 400 },
    desc: 'Eastern European tech powerhouse boasting high-speed digital networks, automotive assembly, and energy reserves.',
    sectors: ['Software & IT', 'Automotive', 'Agriculture', 'Energy Resources']
  },
  {
    name: 'Slovakia',
    code: 'SK',
    flag: '🇸🇰',
    capital: 'Bratislava',
    population: '5.4M',
    popRaw: 5.4,
    joined: 2004,
    gdp: '€120B',
    gdpRaw: 120,
    region: 'Central Europe',
    coordinates: { x: 550, y: 320 },
    desc: 'Global leader in per-capita automobile production, heavily integrated into European industrial supply chains.',
    sectors: ['Automotive Manufacturing', 'Electronics', 'Steel Production', 'Energy']
  },
  {
    name: 'Slovenia',
    code: 'SI',
    flag: '🇸🇮',
    capital: 'Ljubljana',
    population: '2.1M',
    popRaw: 2.1,
    joined: 2004,
    gdp: '€62B',
    gdpRaw: 62,
    region: 'Central Europe',
    coordinates: { x: 490, y: 400 },
    desc: 'Green alpine country with exceptional human development index, advanced pharmaceuticals, and clean energy.',
    sectors: ['Pharmaceuticals', 'High-Tech Manufacturing', 'Tourism', 'Logistics']
  },
  {
    name: 'Spain',
    code: 'ES',
    flag: '🇪🇸',
    capital: 'Madrid',
    population: '48.6M',
    popRaw: 48.6,
    joined: 1986,
    gdp: '€1.5T',
    gdpRaw: 1500,
    region: 'Southern Europe',
    coordinates: { x: 150, y: 550 },
    desc: 'Major European economic power, leader in solar & wind energy generation, high-speed rail, and global cultural reach.',
    sectors: ['Solar & Wind Energy', 'Automotive', 'Tourism', 'High-Speed Infrastructure']
  },
  {
    name: 'Sweden',
    code: 'SE',
    flag: '🇸🇪',
    capital: 'Stockholm',
    population: '10.5M',
    popRaw: 10.5,
    joined: 1995,
    gdp: '€550B',
    gdpRaw: 550,
    region: 'Northern Europe',
    coordinates: { x: 500, y: 100 },
    desc: 'Innovation powerhouse, home of green steel projects, world-class tech unicorns, and social equality.',
    sectors: ['Tech & Startups', 'Green Steel & Mining', 'Automotive & Heavy Industry', 'Telecom']
  }
];

export const EU_INSTITUTIONS = [
  {
    id: 'parliament',
    name: 'European Parliament',
    city: 'Strasbourg / Brussels',
    role: 'Directly-elected EU legislative body representing EU citizens.',
    members: '720 Members (MEPs)',
    functions: [
      'Passes EU laws jointly with the Council of the EU based on Commission proposals',
      'Approves the annual EU budget',
      'Elects the President of the European Commission and holds institutions accountable'
    ]
  },
  {
    id: 'council',
    name: 'European Council',
    city: 'Brussels',
    role: 'Defines the overall political direction and priorities of the European Union.',
    members: 'Heads of State/Government of 27 Member States',
    functions: [
      'Sets strategic policy goals for geopolitical and economic affairs',
      'Deals with complex or sensitive national issues that cannot be resolved at lower levels',
      'Nominates candidates for high-profile EU roles (Commission President, ECB Chief)'
    ]
  },
  {
    id: 'commission',
    name: 'European Commission',
    city: 'Brussels',
    role: 'Politically independent executive arm of the EU.',
    members: 'College of 27 Commissioners (one per Member State)',
    functions: [
      'Proposes new legislation for Parliament and Council review',
      'Manages EU policies and executes the allocated annual budget',
      'Enforces EU law as the "Guardian of the Treaties"'
    ]
  },
  {
    id: 'ecb',
    name: 'European Central Bank (ECB)',
    city: 'Frankfurt am Main',
    role: 'Central bank for the 20 EU member countries using the Euro.',
    members: 'Governing Council & Executive Board',
    functions: [
      'Maintains price stability and targets a 2% inflation rate in the Eurozone',
      'Sets key benchmark interest rates for commercial banking',
      'Supervises major Eurozone credit institutions and financial stability'
    ]
  }
];
